import { Brand } from "@/app/ui/features";
import { GoBack } from "@/app/ui/features/GoBack";
import { GoHomeFill } from "@/app/ui/icons";
import { Locale } from "@/i18n-config";
import { Button } from "antd";
import type { Metadata } from "next";
import Link from "next/link";
import { images } from "./usuario/components/data";
import { SlideShow } from "./usuario/components/SlideShow";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <main className="relative flex min-h-lvh items-center justify-center lg:p-10">
      <section className="absolute bottom-0 left-0 right-0 top-0 z-[2] grid grid-cols-1 bg-white xs:p-2 sm:max-w-5xl lg:relative lg:grid-cols-[3fr_2fr] lg:rounded-md">
        <SlideShow images={images} className="relative hidden lg:flex" />
        <article className="m-auto grid max-w-lg grid-cols-1 grid-rows-1 flex-col rounded-md bg-white p-2 lg:rounded-bl-none lg:rounded-tl-none lg:px-4">
          <div className="grid grid-cols-1 grid-rows-[1fr_auto_auto]">
            <div className="rounded-m flex flex-col items-center justify-center self-center rounded-md border bg-white p-4 shadow-md lg:h-auto lg:p-2 lg:px-6">
              <div className="flex w-full justify-between p-1 px-0">
                <GoBack />
                <Link href="/">
                  <Button
                    type="default"
                    icon={<GoHomeFill className="text-neutral-500" />}
                    size={"large"}
                    className="!flex items-center justify-center"
                  />
                </Link>
              </div>

              <div className="mb-4 flex flex-col items-center justify-center">
                <Brand className="my-8 lg:my-4" />
              </div>
              {children}
            </div>
            <div className="flex -translate-y-[1px] justify-center">
              <div className="w-4/5">
                <div className="h-[1px] w-full bg-gradient-to-r from-transparent via-primary-400 to-transparent"></div>
              </div>
            </div>
            <div className="my-2 flex items-center justify-center">
              <p className="text-center text-xs font-medium">
                Already have an account?{" "}
                <Link
                  href={`/${lang}/iniciar-session`}
                  className="ml-2 text-primary-500 underline"
                >
                  Sign in
                </Link>
              </p>
            </div>
          </div>
        </article>
      </section>
      <div className="absolute bottom-0 left-0 right-0 top-0 z-[1] rounded-md bg-black/20 backdrop-blur-xl backdrop-filter" />
      <div className="absolute bottom-0 left-0 right-0 top-0 bg-[url('/assets/images/auth/photograph-behind-plant-on-the-table-during-sunset-at-the-hotel-quinto-nivel-rd.webp')] bg-cover bg-center bg-no-repeat" />
    </main>
  );
}
