import type { TableColumnsType } from "antd";
import { format } from "@/utils/formatter/format";

type Guest = {
  key: string;
  verified: "Yes" | "No";
  avatar: string;
  name: string;
  lastName: string;
  gender: string;
  dateOfBirth: string;
  age: number;
  phone: string;
  email: string;
  totalReservations: number;
  lastVisit: string;
  accountType: string;
  accountStatus: string;
  identification: "Cedula" | "Passport";
  pendingBalance: string;
};

export const dataSource: Guest[] = [
  {
    key: "1",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/male/0.jpg",
    name: "Mitchell",
    lastName: "Bergnaum",
    gender: "male",
    dateOfBirth: "10/19/1970",
    age: 53,
    email: "mitchell_bergnaum67@hotmail.com",
    phone: "920-042-1986",
    totalReservations: 19,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Passport",
    pendingBalance: "$121.00",
  },
  {
    key: "2",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/male/1.jpg",
    name: "Lucas",
    lastName: "Wunsch",
    gender: "male",
    dateOfBirth: "09/28/1993",
    age: 30,
    email: "lucas_wunsch@hotmail.com",
    phone: "260-976-5589",
    totalReservations: 17,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$4576.00",
  },
  {
    key: "3",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/female/2.jpg",
    name: "Toni",
    lastName: "Hintz",
    gender: "female",
    dateOfBirth: "12/20/1932",
    age: 91,
    email: "toni_hintz56@gmail.com",
    phone: "513-627-2828",
    totalReservations: 2,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$253.00",
  },
  {
    key: "4",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/female/3.jpg",
    name: "Cecelia",
    lastName: "Pacocha",
    gender: "female",
    dateOfBirth: "07/05/1964",
    age: 59,
    email: "cecelia_pacocha7@gmail.com",
    phone: "347-241-5042",
    totalReservations: 8,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$3857.00",
  },
  {
    key: "5",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/male/4.jpg",
    name: "Darren",
    lastName: "Lesch",
    gender: "male",
    dateOfBirth: "02/10/1995",
    age: 29,
    email: "darren.lesch@hotmail.com",
    phone: "614-935-7441",
    totalReservations: 2,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Passport",
    pendingBalance: "$4660.00",
  },
  {
    key: "6",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/female/5.jpg",
    name: "Kara",
    lastName: "Jacobs",
    gender: "female",
    dateOfBirth: "02/09/1940",
    age: 84,
    email: "kara.jacobs80@yahoo.com",
    phone: "061-490-3825",
    totalReservations: 12,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$233.00",
  },
  {
    key: "7",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/male/6.jpg",
    name: "Glen",
    lastName: "Schmeler",
    gender: "male",
    dateOfBirth: "06/18/1981",
    age: 42,
    email: "glen.schmeler34@gmail.com",
    phone: "976-164-9065",
    totalReservations: 5,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Cedula",
    pendingBalance: "$4638.00",
  },
  {
    key: "8",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/male/7.jpg",
    name: "Robin",
    lastName: "Hansen",
    gender: "male",
    dateOfBirth: "06/29/1962",
    age: 61,
    email: "robin_hansen@yahoo.com",
    phone: "083-788-6295",
    totalReservations: 19,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$1594.00",
  },
  {
    key: "9",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/male/8.jpg",
    name: "Clayton",
    lastName: "Dickinson",
    gender: "male",
    dateOfBirth: "12/19/1987",
    age: 36,
    email: "clayton.dickinson@gmail.com",
    phone: "088-868-7441",
    totalReservations: 18,
    lastVisit: "05/17/2024",
    accountType: "Manager",
    accountStatus: "Inactive",
    identification: "Passport",
    pendingBalance: "$4162.00",
  },
  {
    key: "10",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/female/9.jpg",
    name: "Gretchen",
    lastName: "Murray",
    gender: "female",
    dateOfBirth: "01/16/1976",
    age: 48,
    email: "gretchen.murray63@hotmail.com",
    phone: "803-026-2308",
    totalReservations: 5,
    lastVisit: "05/17/2024",
    accountType: "Developer",
    accountStatus: "Inactive",
    identification: "Cedula",
    pendingBalance: "$4314.00",
  },
  {
    key: "11",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/male/10.jpg",
    name: "Gregory",
    lastName: "Gutmann",
    gender: "male",
    dateOfBirth: "10/09/1939",
    age: 84,
    email: "gregory.gutmann@hotmail.com",
    phone: "337-475-0511",
    totalReservations: 7,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Cedula",
    pendingBalance: "$2712.00",
  },
  {
    key: "12",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/male/11.jpg",
    name: "Irving",
    lastName: "Satterfield",
    gender: "male",
    dateOfBirth: "10/23/1933",
    age: 90,
    email: "irving.satterfield@hotmail.com",
    phone: "606-519-8519",
    totalReservations: 5,
    lastVisit: "05/17/2024",
    accountType: "Supervisor",
    accountStatus: "Inactive",
    identification: "Passport",
    pendingBalance: "$1466.00",
  },
  {
    key: "13",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/female/12.jpg",
    name: "Brandy",
    lastName: "Frami",
    gender: "female",
    dateOfBirth: "07/16/1996",
    age: 27,
    email: "brandy.frami34@hotmail.com",
    phone: "986-610-2844",
    totalReservations: 2,
    lastVisit: "05/17/2024",
    accountType: "Receptionist",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$3650.00",
  },
  {
    key: "14",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/female/13.jpg",
    name: "Nora",
    lastName: "Schaden",
    gender: "female",
    dateOfBirth: "07/01/1954",
    age: 69,
    email: "nora_schaden@hotmail.com",
    phone: "023-590-9640",
    totalReservations: 0,
    lastVisit: "05/17/2024",
    accountType: "Receptionist",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$1530.00",
  },
  {
    key: "15",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/female/14.jpg",
    name: "Kathy",
    lastName: "Schulist",
    gender: "female",
    dateOfBirth: "03/05/1985",
    age: 39,
    email: "kathy.schulist@gmail.com",
    phone: "492-956-6206",
    totalReservations: 9,
    lastVisit: "05/17/2024",
    accountType: "CEO",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$567.00",
  },
  {
    key: "16",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/female/15.jpg",
    name: "Dixie",
    lastName: "Daniel-Zboncak",
    gender: "female",
    dateOfBirth: "02/28/1950",
    age: 74,
    email: "dixie.daniel-zboncak93@yahoo.com",
    phone: "256-168-2408",
    totalReservations: 0,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Passport",
    pendingBalance: "$1571.00",
  },
  {
    key: "17",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/male/16.jpg",
    name: "Allan",
    lastName: "Bernhard",
    gender: "male",
    dateOfBirth: "05/19/2001",
    age: 22,
    email: "allan.bernhard@hotmail.com",
    phone: "024-582-2750",
    totalReservations: 10,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Cedula",
    pendingBalance: "$698.00",
  },
  {
    key: "18",
    verified: "Yes",
    avatar: "https://randomuser.me/api/portraits/female/17.jpg",
    name: "Kay",
    lastName: "Ernser",
    gender: "female",
    dateOfBirth: "06/21/1978",
    age: 45,
    email: "kay.ernser@hotmail.com",
    phone: "941-123-5345",
    totalReservations: 20,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
    pendingBalance: "$1919.00",
  },
  {
    key: "19",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/female/18.jpg",
    name: "Lauren",
    lastName: "Kling",
    gender: "female",
    dateOfBirth: "08/09/1989",
    age: 34,
    email: "lauren.kling@hotmail.com",
    phone: "333-639-0084",
    totalReservations: 19,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Cedula",
    pendingBalance: "$2338.00",
  },
  {
    key: "20",
    verified: "No",
    avatar: "https://randomuser.me/api/portraits/female/19.jpg",
    name: "Katie",
    lastName: "Macejkovic",
    gender: "female",
    dateOfBirth: "07/13/1976",
    age: 47,
    email: "katie_macejkovic17@gmail.com",
    phone: "139-596-1328",
    totalReservations: 14,
    lastVisit: "05/17/2024",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Passport",
    pendingBalance: "$1301.00",
  },
];

export const columns: TableColumnsType<Guest> = [
  {
    title: "Verfied",
    dataIndex: "verified",
    key: "verified",
  },
  {
    title: "Identification",
    dataIndex: "identification",
    key: "identification",
  },
  {
    title: "Name",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "Last Name",
    dataIndex: "lastName",
    key: "lastName",
  },
  {
    title: "Gender",
    dataIndex: "gender",
    key: "gender",
  },
  {
    title: "Date of Birth",
    dataIndex: "dateOfBirth",
    key: "dateOfBirth",
  },
  {
    title: "Age",
    dataIndex: "age",
    key: "age",
  },
  {
    title: "Phone",
    dataIndex: "phone",
    key: "phone",
  },
  {
    title: "Email",
    dataIndex: "email",
    key: "email",
  },
  {
    title: "Total Reservations",
    dataIndex: "totalReservations",
    key: "totalReservations",
  },
  {
    title: "Last Visit",
    dataIndex: "lastVisit",
    key: "lastVisit",
  },
  {
    title: "Balance",
    dataIndex: "pendingBalance",
    key: "pendingBalance",
  },
  {
    title: "Account Type",
    dataIndex: "accountType",
    key: "accountType",
  },
  {
    title: "Account Status",
    dataIndex: "accountStatus",
    key: "accountStatus",
  },
];
