import type { TableColumnsType } from "antd";
import { format } from "@/utils/formatter/format";
import { Guest } from "@/types";

export const dataSource: Guest[] = [
  {
    key: "1",
    verified: "No",
    name: "Mitchell",
    lastName: "Bergnaum",
    gender: "male",
    dateOfBirth: "10/19/1970",
    age: 53,
    email: "mitchell_bergnaum67@hotmail.com",
    phone: "920-042-1986",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Passport",
  },
  {
    key: "2",
    verified: "No",
    name: "Lucas",
    lastName: "Wunsch",
    gender: "male",
    dateOfBirth: "09/28/1993",
    age: 30,
    email: "lucas_wunsch@hotmail.com",
    phone: "260-976-5589",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "3",
    verified: "Yes",
    name: "Toni",
    lastName: "Hintz",
    gender: "female",
    dateOfBirth: "12/20/1932",
    age: 91,
    email: "toni_hintz56@gmail.com",
    phone: "513-627-2828",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "4",
    verified: "No",
    name: "Cecelia",
    lastName: "Pacocha",
    gender: "female",
    dateOfBirth: "07/05/1964",
    age: 59,
    email: "cecelia_pacocha7@gmail.com",
    phone: "347-241-5042",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "5",
    verified: "Yes",
    name: "Darren",
    lastName: "Lesch",
    gender: "male",
    dateOfBirth: "02/10/1995",
    age: 29,
    email: "darren.lesch@hotmail.com",
    phone: "614-935-7441",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Passport",
  },
  {
    key: "6",
    verified: "Yes",
    name: "Kara",
    lastName: "Jacobs",
    gender: "female",
    dateOfBirth: "02/09/1940",
    age: 84,
    email: "kara.jacobs80@yahoo.com",
    phone: "061-490-3825",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "7",
    verified: "Yes",
    name: "Glen",
    lastName: "Schmeler",
    gender: "male",
    dateOfBirth: "06/18/1981",
    age: 42,
    email: "glen.schmeler34@gmail.com",
    phone: "976-164-9065",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Cedula",
  },
  {
    key: "8",
    verified: "No",
    name: "Robin",
    lastName: "Hansen",
    gender: "male",
    dateOfBirth: "06/29/1962",
    age: 61,
    email: "robin_hansen@yahoo.com",
    phone: "083-788-6295",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "9",
    verified: "Yes",
    name: "Clayton",
    lastName: "Dickinson",
    gender: "male",
    dateOfBirth: "12/19/1987",
    age: 36,
    email: "clayton.dickinson@gmail.com",
    phone: "088-868-7441",
    accountType: "Manager",
    accountStatus: "Inactive",
    identification: "Passport",
  },
  {
    key: "10",
    verified: "No",
    name: "Gretchen",
    lastName: "Murray",
    gender: "female",
    dateOfBirth: "01/16/1976",
    age: 48,
    email: "gretchen.murray63@hotmail.com",
    phone: "803-026-2308",
    accountType: "Developer",
    accountStatus: "Inactive",
    identification: "Cedula",
  },
  {
    key: "11",
    verified: "Yes",
    name: "Gregory",
    lastName: "Gutmann",
    gender: "male",
    dateOfBirth: "10/09/1939",
    age: 84,
    email: "gregory.gutmann@hotmail.com",
    phone: "337-475-0511",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Cedula",
  },
  {
    key: "12",
    verified: "Yes",
    name: "Irving",
    lastName: "Satterfield",
    gender: "male",
    dateOfBirth: "10/23/1933",
    age: 90,
    email: "irving.satterfield@hotmail.com",
    phone: "606-519-8519",
    accountType: "Supervisor",
    accountStatus: "Inactive",
    identification: "Passport",
  },
  {
    key: "13",
    verified: "Yes",
    name: "Brandy",
    lastName: "Frami",
    gender: "female",
    dateOfBirth: "07/16/1996",
    age: 27,
    email: "brandy.frami34@hotmail.com",
    phone: "986-610-2844",
    accountType: "Receptionist",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "14",
    verified: "No",
    name: "Nora",
    lastName: "Schaden",
    gender: "female",
    dateOfBirth: "07/01/1954",
    age: 69,
    email: "nora_schaden@hotmail.com",
    phone: "023-590-9640",
    accountType: "Receptionist",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "15",
    verified: "Yes",
    name: "Kathy",
    lastName: "Schulist",
    gender: "female",
    dateOfBirth: "03/05/1985",
    age: 39,
    email: "kathy.schulist@gmail.com",
    phone: "492-956-6206",
    accountType: "CEO",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "16",
    verified: "No",
    name: "Dixie",
    lastName: "Daniel-Zboncak",
    gender: "female",
    dateOfBirth: "02/28/1950",
    age: 74,
    email: "dixie.daniel-zboncak93@yahoo.com",
    phone: "256-168-2408",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Passport",
  },
  {
    key: "17",
    verified: "Yes",
    name: "Allan",
    lastName: "Bernhard",
    gender: "male",
    dateOfBirth: "05/19/2001",
    age: 22,
    email: "allan.bernhard@hotmail.com",
    phone: "024-582-2750",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Cedula",
  },
  {
    key: "18",
    verified: "Yes",
    name: "Kay",
    lastName: "Ernser",
    gender: "female",
    dateOfBirth: "06/21/1978",
    age: 45,
    email: "kay.ernser@hotmail.com",
    phone: "941-123-5345",
    accountType: "Guest",
    accountStatus: "Active",
    identification: "Passport",
  },
  {
    key: "19",
    verified: "No",
    name: "Lauren",
    lastName: "Kling",
    gender: "female",
    dateOfBirth: "08/09/1989",
    age: 34,
    email: "lauren.kling@hotmail.com",
    phone: "333-639-0084",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Cedula",
  },
  {
    key: "20",
    verified: "No",
    name: "Katie",
    lastName: "Macejkovic",
    gender: "female",
    dateOfBirth: "07/13/1976",
    age: 47,
    email: "katie_macejkovic17@gmail.com",
    phone: "139-596-1328",
    accountType: "Guest",
    accountStatus: "Inactive",
    identification: "Passport",
  },
];

export const columns: TableColumnsType<Guest> = [
  {
    title: "Name",
    dataIndex: "name",
    key: "name",
  },
  {
    title: "Last Name",
    dataIndex: "lastName",
    key: "lastName",
  },
  {
    title: "Gender",
    dataIndex: "gender",
    key: "gender",
  },
  {
    title: "Date of Birth",
    dataIndex: "dateOfBirth",
    key: "dateOfBirth",
  },
  {
    title: "Age",
    dataIndex: "age",
    key: "age",
  },
  {
    title: "Phone",
    dataIndex: "phone",
    key: "phone",
  },
  {
    title: "Email",
    dataIndex: "email",
    key: "email",
  },
  {
    title: "Verfied",
    dataIndex: "verified",
    key: "verified",
  },
  {
    title: "Identification",
    dataIndex: "identification",
    key: "identification",
  },
  {
    title: "Account Type",
    dataIndex: "accountType",
    key: "accountType",
  },
  {
    title: "Account Status",
    dataIndex: "accountStatus",
    key: "accountStatus",
  },
];
