import { AntdRegistry } from "@ant-design/nextjs-registry";

import type { Metadata } from "next";
import "../../ui/styles/globals.css";
import { poppins } from "../../ui/typography";

import { Locale, i18n } from "@/i18n-config";
import AntConfigProvider from "@/providers/ConfigProvider";
import { CONSTANTS } from "@/utils/constants";

export const metadata: Metadata = {
  title: `${CONSTANTS.Brand.COMPANY_NAME} - Home`,
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang} className="min-h-dvh">
      <body
        className={`${poppins.className} grid min-h-dvh grid-cols-1 grid-rows-[auto_1fr]`}
      >
        <AntConfigProvider lang={lang}>
          <AntdRegistry>{children}</AntdRegistry>
        </AntConfigProvider>
      </body>
    </html>
  );
}
