import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import "../../ui/styles/globals.css";
import { poppins } from "../../ui/typography";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Locale, i18n } from "@/i18n-config";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang}>
      <body className={poppins.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
