import { HeaderContent } from "@/app/ui/components/site/Rooms/HeaderContent";
import { Header, PublicLayout, Wrapper } from "@/app/ui/layout";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Hotel Quinto Nivel RD | Habitaciones",
  description: "Generated by create next app",
};

import { Locale, i18n } from "@/i18n-config";
import { getUser } from "@/utils/supabase/queries";
import { billboards } from "../../../../public/assets/data/billbaord";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default async function RoomsLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  //@ts-ignore
  const user: UserProfileTypes = await getUser();
  return (
    <PublicLayout lang={lang} user={user}>
      <Wrapper className="p-0 pt-[57px] md:pt-[0]">
        <Header className="flex h-[calc(100vh-60vh)] items-stretch justify-stretch p-2 md:h-[calc(100vh-40vh)] md:pt-[60px]">
          <HeaderContent lang={lang} billboards={billboards} />
        </Header>
      </Wrapper>
      <main className="flex flex-col items-center pb-36">{children}</main>
    </PublicLayout>
  );
}
