import { AntdRegistry } from "@ant-design/nextjs-registry";

import type { Metadata } from "next";
import "../../../ui/styles/globals.css";
import { poppins } from "../../../ui/typography";

import { Aside, Main } from "@/app/ui/components/dashboard/layout";
import { Locale, i18n } from "@/i18n-config";
import AntConfigProvider from "@/providers/ConfigProvider";
import { CONSTANTS } from "@/utils/constants";

export const metadata: Metadata = {
  title: `${CONSTANTS.Brand.COMPANY_NAME} - Home`,
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function DashboardLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang} className="min-h-dvh">
      <body className={`${poppins.className}`}>
        <section
          className={`grid min-h-dvh grid-rows-[1fr_auto] md:grid-cols-[auto_1fr]`}
        >
          <AntConfigProvider lang={lang}>
            <AntdRegistry>
              <Aside lang={lang} className="order-1 md:order-1" />
              <Main className="md:order-2" lang={lang}>
                {children}
              </Main>
            </AntdRegistry>
          </AntConfigProvider>
        </section>
      </body>
    </html>
  );
}
