import { AntdRegistry } from "@ant-design/nextjs-registry";

import type { Metadata } from "next";
import "../../../ui/styles/globals.css";
import { poppins } from "../../../ui/typography";

import { Locale, i18n } from "@/i18n-config";
import AntConfigProvider from "@/providers/ConfigProvider";
import { CONSTANTS } from "@/utils/constants";
import { Aside, Main } from "@/app/ui/components/dashboard";

export const metadata: Metadata = {
  title: `${CONSTANTS.Brand.COMPANY_NAME} - Home`,
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function DashboardLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang} className="min-h-dvh">
      <body
        className={`${poppins.className} grid min-h-dvh grid-cols-1 grid-rows-[auto_1fr]`}
      >
        <AntConfigProvider lang={lang}>
          <AntdRegistry>
            <section className="flex min-h-dvh flex-col justify-end sm:flex-row">
              <Aside lang={lang} className="z-[10] order-last sm:order-first" />
              <Main className="flex-[8] overflow-auto" lang={lang}>
                {children}
              </Main>
            </section>
          </AntdRegistry>
        </AntConfigProvider>
      </body>
    </html>
  );
}
