import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Brand } from "@/app/ui/components";
import { Locale } from "@/i18n-config";
import { Button } from "antd";
import Link from "next/link";
import { GoHomeFill } from "react-icons/go";
import { images } from "./usuario/components/data";
import { SlideShow } from "./usuario/components/SlideShow";
import { GoBack } from "@/app/ui/common/GoBack";

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <main className="min-h-dvh flex items-center justify-center relative">
      <section className="sm:max-w-5xl grid grid-cols-1 sm:grid-cols-[3fr_2fr] z-[2] xs:p-2 absolute top-0 left-0 right-0 bottom-0 bg-white lg:relative lg:rounded-md">
        <SlideShow images={images} className="hidden sm:flex relative" />
        <article className="bg-white sm:px-4 grid grid-cols-1 grid-rows-1 rounded-md p-2 flex-col sm:rounded-tl-none sm:rounded-bl-none">
          <div className="grid grid-cols-1 grid-rows-[1fr_auto_auto]">
            <div className="self-center border  sm:h-auto p-3 sm:p-2 sm:px-6 shadow-md rounded-md flex items-center justify-center flex-col bg-white rounded-m">
              <div className="flex justify-between w-full py-2">
                <GoBack />
                <Link href="/">
                  <GoHomeFill className="text-neutral-500" />
                </Link>
              </div>
              <div className="flex items-center justify-center flex-col mb-4">
                <Brand className="my-8 sm:my-4" />
              </div>
              {children}
            </div>
            <div className="flex justify-center -translate-y-[1px]">
              <div className="w-4/5">
                <div className="h-[1px] bg-gradient-to-r from-transparent via-primary-400 to-transparent w-full"></div>
              </div>
            </div>
            <div className="my-2 flex items-center justify-center">
              <p className="text-xs font-medium text-center">
                Already have an account?{" "}
                <Link
                  href={`/${lang}/iniciar-session`}
                  className="ml-2 underline text-primary-500"
                >
                  Sign in
                </Link>
              </p>
            </div>
          </div>
        </article>
      </section>
      <div className="bg-black/20 absolute top-0 left-0 right-0 bottom-0 rounded-md backdrop-filter backdrop-blur-xl z-[1]" />
      <div className="bg-[url('/assets/images/auth/photograph-behind-plant-on-the-table-during-sunset-at-the-hotel-quinto-nivel-rd.webp')] bg-no-repeat bg-center bg-cover absolute top-0 left-0 right-0 bottom-0" />
    </main>
  );
}
