import { AntdRegistry } from "@ant-design/nextjs-registry";
import { Header, PublicLayout, Wrapper } from "@/app/ui/layout";
import type { Metadata } from "next";
import { HeaderContent } from "@/app/ui/components/Rooms/HeaderContent";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Locale, i18n } from "@/i18n-config";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RoomsLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <PublicLayout lang={lang}>
      <Wrapper className="p-0 pt-[57px] md:pt-[0]">
        <Header className="flex h-[calc(100vh-60vh)] items-stretch justify-stretch p-2 md:h-[calc(100vh-40vh)] md:pt-[60px]">
          <HeaderContent lang={lang} />
        </Header>
      </Wrapper>
      <main className="flex flex-col items-center pb-36">{children}</main>
    </PublicLayout>
  );
}
