export const rooms = [
  {
    id: 1,
    roomNumber: 101,
    slug: "doble-camas",
    category: "Double Bed",
  },
  {
    id: 2,
    roomNumber: 102,
    slug: "doble",
    category: "Double Room",
  },
  {
    id: 3,
    roomNumber: 103,
    slug: "basicas",
    category: "Basic Room",
  },
  {
    id: 3,
    roomNumber: 104,
    slug: "basicas",
    category: "Basic Room",
  },
  {
    id: 4,
    roomNumber: 205,
    slug: "familiares",
    category: "Familiar Room",
  },
  {
    id: 5,
    roomNumber: 208,
    slug: "ejecutivas",
    category: "Executive Room",
  },
  {
    id: 6,
    roomNumber: 301,
    slug: "ejecutivas",
    category: "Executive Room",
  },
  {
    id: 7,
    roomNumber: 505,
    slug: "familiares",
    category: "Familiar Room",
  },
  {
    id: 8,
    roomNumber: 403,
    slug: "ejecutivas",
    category: "Executive Room",
  },
  {
    id: 9,
    roomNumber: 204,
    slug: "ejecutivas",
    category: "Executive Room",
  },
  {
    id: 10,
    roomNumber: 202,
    slug: "standards",
    category: "Standard Room",
  },
  {
    id: 11,
    roomNumber: 504,
    slug: "basicas",
    category: "Basic Room",
  },
  {
    id: 12,
    roomNumber: 206,
    slug: "ejecutivas",
    category: "Executive Room",
  },
  {
    id: 13,
    roomNumber: 503,
    slug: "basicas",
    category: "Basic Room",
  },
  {
    id: 14,
    roomNumber: 302,
    slug: "standards",
    category: "Standard Room",
  },
  {
    id: 15,
    roomNumber: 102,
    slug: "double-bed",
    category: "Double Room",
  },
  {
    id: 16,
    roomNumber: 306,
    slug: "double-bed",
    category: "Double Room",
  },
];
