import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";

import type { Metadata } from "next";
import { poppins } from "../ui/typography";
import "./../ui/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Locale, i18n } from "@/i18n-config";
import deDE from "antd/locale/de_DE";
import enUS from "antd/locale/en_US";
import esES from "antd/locale/es_ES";
import { FontUnitProvider } from "../ui/typography/FontUnitProvider";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang} className={"min-h-dvh"}>
      <body className={`${poppins.className} min-h-dvh`}>
        <ConfigProvider
          locale={lang === "de" ? deDE : lang === "en" ? enUS : esES}
          theme={{
            cssVar: { key: "app" },
            token: {
              colorPrimary: "#1a73b2",
            },
          }}
        >
          <FontUnitProvider>
            <AntdRegistry>{children}</AntdRegistry>
          </FontUnitProvider>
        </ConfigProvider>
      </body>
    </html>
  );
}
