import { AntdRegistry } from "@ant-design/nextjs-registry";

import type { Metadata } from "next";
import { poppins } from "../ui/typography";
import "./../ui/styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Locale, i18n } from "@/i18n-config";
import { FontUnitProvider } from "../ui/typography/FontUnitProvider";
import AntConfigProvider from "@/providers/ConfigProvider";
import Link from "next/link";

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({
  children,
  params: { lang },
}: Readonly<{
  children: React.ReactNode;
  params: { lang: Locale };
}>) {
  return (
    <html lang={lang} className={"min-h-dvh"}>
      <body
        className={`${poppins.className} min-h-dvh antialiased bg-[#fefefe] text-[#242424]`}
      >
        <AntConfigProvider lang={lang}>
          <AntdRegistry>
            <nav className="flex gap-2 text-sm p-2">
              <Link href="/" locale={lang}>
                Home
              </Link>
              <Link href="/about" locale={lang}>
                About
              </Link>
              <Link href="/playground" locale={lang}>
                Playground
              </Link>
            </nav>
            {children}
          </AntdRegistry>
        </AntConfigProvider>
      </body>
    </html>
  );
}
