import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import "../ui/styles/globals.css";
import { poppins } from "../ui/typography";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
